name: webgpu
description: The WebGPU API for Flutter. Enables developers to use the underlying system's GPU (Graphics Processing Unit) to carry out high-performance computations and draw complex images that can be rendered in the browser.
version: 0.0.1
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_webgpu

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  web: ^1.1.1

dev_dependencies:
  test: ^1.25.15
  lints: ^5.1.1

